#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# OPL Cheat Injector Script by SailorM
# Version 0.1a (prototype)
#
# Scan it. Match it. Inject it.
# Yeppers fuckers.
#
# Cheat data source:
# https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats
# Cheat-file credit belongs to that project and its contributors.
# ============================================================

CACHE="$HOME/.cache/opl-cheat-injector"
TRUSTED_REPO="$CACHE/opl-widescreen-cheats"
TRUSTED_REPO_URL="https://github.com/PS2-Widescreen/OPL-Widescreen-Cheats.git"

MANAGED_TAG="# Generated by OPL Cheat Injector Script by SailorM v0.1a"
MANAGED_PREFIX="# Generated by OPL Cheat Injector Script by SailorM v"

SERIAL_REGEX='(SLUS|SCUS|SLES|SCES|SLPS|SLPM|SCPS|SCAJ|SCKA|SLKA|SCCS)[_-]?[0-9]{3}[.]?[0-9]{2}'

echo
echo "============================================================"
echo " OPL CHEAT INJECTOR SCRIPT"
echo " by SailorM"
echo " v0.1a prototype"
echo "============================================================"
echo

# ------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------

for cmd in git grep sed awk find dd strings sort; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "ERROR: Missing dependency: $cmd"
        exit 1
    fi
done

# ------------------------------------------------------------
# Command-line options
# ------------------------------------------------------------

REQUESTED_ROOT=""

usage() {
    cat <<'EOF'
Usage:
  ./opl-cheat-injector.sh
  ./opl-cheat-injector.sh --root /path/to/OPL/device
  ./opl-cheat-injector.sh /path/to/OPL/device

With no path, the script safely detects likely mounted OPL devices.
EOF
}

while (( $# > 0 )); do
    case "$1" in
        --root)
            if (( $# < 2 )); then
                echo "ERROR: --root requires a path."
                usage
                exit 2
            fi
            REQUESTED_ROOT="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        --)
            shift
            if (( $# > 0 )); then
                REQUESTED_ROOT="$1"
                shift
            fi
            ;;
        -*)
            echo "ERROR: Unknown option: $1"
            usage
            exit 2
            ;;
        *)
            if [[ -n "$REQUESTED_ROOT" ]]; then
                echo "ERROR: Only one OPL root may be selected."
                usage
                exit 2
            fi
            REQUESTED_ROOT="$1"
            shift
            ;;
    esac
done

# ------------------------------------------------------------
# Locate an OPL device safely
# ------------------------------------------------------------

is_opl_root() {
    local path="$1"

    [[ -d "$path" ]] || return 1
    [[ -d "$path/DVD" || -d "$path/CD" || -d "$path/CHT" ]]
}

canonical_directory() {
    local path="$1"

    (cd -- "$path" 2>/dev/null && pwd -P)
}

declare -a OPL_CANDIDATES=()
declare -A SEEN_CANDIDATES=()

add_candidate() {
    local path="$1"
    local canonical

    is_opl_root "$path" || return 0
    canonical="$(canonical_directory "$path" || true)"
    [[ -n "$canonical" ]] || return 0

    if [[ -z "${SEEN_CANDIDATES[$canonical]+x}" ]]; then
        OPL_CANDIDATES+=("$canonical")
        SEEN_CANDIDATES["$canonical"]=1
    fi
}

select_opl_root() {
    local script_directory
    local selected
    local reply
    local path
    local index

    if [[ -n "$REQUESTED_ROOT" ]]; then
        if ! is_opl_root "$REQUESTED_ROOT"; then
            echo "ERROR: This does not look like an OPL device root:" >&2
            echo "  $REQUESTED_ROOT" >&2
            echo "Expected at least one of these directories: DVD, CD, CHT" >&2
            exit 1
        fi

        canonical_directory "$REQUESTED_ROOT"
        return
    fi

    script_directory="$(
        cd -- "$(dirname -- "${BASH_SOURCE[0]}")" 2>/dev/null && pwd -P
    )"

    add_candidate "$script_directory"
    add_candidate "$PWD"

    shopt -s nullglob
    for path in \
        /media/*/* \
        /run/media/*/* \
        /mnt/* \
        /Volumes/*; do
        add_candidate "$path"
    done
    shopt -u nullglob

    if (( ${#OPL_CANDIDATES[@]} == 1 )); then
        printf '%s\n' "${OPL_CANDIDATES[0]}"
        return
    fi

    if (( ${#OPL_CANDIDATES[@]} > 1 )); then
        if [[ ! -t 0 ]]; then
            echo "ERROR: Multiple OPL devices found; use --root PATH." >&2
            for path in "${OPL_CANDIDATES[@]}"; do
                echo "  $path" >&2
            done
            exit 1
        fi

        echo "Multiple OPL devices found:" >&2
        echo >&2
        for index in "${!OPL_CANDIDATES[@]}"; do
            printf '%d) %s\n' "$((index + 1))" "${OPL_CANDIDATES[index]}" >&2
        done
        echo >&2

        while true; do
            read -r -p "Select device [1-${#OPL_CANDIDATES[@]}]: " reply
            if [[ "$reply" =~ ^[0-9]+$ ]] &&
                (( reply >= 1 && reply <= ${#OPL_CANDIDATES[@]} )); then
                selected="${OPL_CANDIDATES[reply - 1]}"
                printf '%s\n' "$selected"
                return
            fi
            echo "Please enter a number from 1 to ${#OPL_CANDIDATES[@]}." >&2
        done
    fi

    if [[ ! -t 0 ]]; then
        echo "ERROR: No OPL device detected; use --root PATH." >&2
        exit 1
    fi

    echo "No OPL device was detected automatically." >&2
    while true; do
        read -r -p "Enter the OPL device root path: " reply

        if is_opl_root "$reply"; then
            canonical_directory "$reply"
            return
        fi

        echo "That path does not contain a DVD, CD, or CHT directory." >&2
    done
}

OPL_ROOT="$(select_opl_root)"
DVD="$OPL_ROOT/DVD"
CD="$OPL_ROOT/CD"
CHT="$OPL_ROOT/CHT"
QUARANTINE="$OPL_ROOT/CHT_UNVERIFIED"

mkdir -p "$CHT" "$QUARANTINE" "$CACHE"

echo "[DEVICE] OPL storage selected:"
echo "         $OPL_ROOT"
echo

# ------------------------------------------------------------
# Fetch/update trusted native CHT repository
# ------------------------------------------------------------

if [[ -d "$TRUSTED_REPO/.git" ]]; then
    echo "[UPDATE] Refreshing trusted OPL cheat repository..."
    git -C "$TRUSTED_REPO" pull --ff-only >/dev/null 2>&1 || {
        echo "[WARN] Repository update failed."
        echo "       Using cached copy."
    }
else
    echo "[DOWNLOAD] Fetching trusted OPL cheat repository..."
    git clone --depth 1 "$TRUSTED_REPO_URL" "$TRUSTED_REPO"
fi

echo

# ------------------------------------------------------------
# Extract and normalize a PS2 serial from arbitrary text.
#
# Supports:
# SLUS_211.34
# SLUS-21134
# SLUS_21134
# SLES_537.02
# ------------------------------------------------------------

extract_serial() {
    local text="$1"

    printf '%s\n' "$text" |
        grep -Eiom1 "$SERIAL_REGEX" |
        tr '[:lower:]' '[:upper:]'
}

# ------------------------------------------------------------
# Read a serial from a game's filename or ISO contents.
#
# OPL-style filenames are checked first. For an ISO without a
# serial in its filename, scan the first 64 MiB; SYSTEM.CNF and
# its BOOT2 executable entry are normally near the beginning.
#
# ZSO contents are compressed, so ZSO games must currently have
# an OPL serial in their filename.
# ------------------------------------------------------------

get_game_serial() {
    local game="$1"
    local filename
    local serial

    filename="$(basename "$game")"
    serial="$(extract_serial "$filename" || true)"

    if [[ -n "$serial" ]]; then
        printf '%s\n' "$serial"
        return 0
    fi

    if [[ "${game,,}" == *.iso ]]; then
        serial="$(
            dd if="$game" bs=1M count=64 status=none 2>/dev/null |
                strings -n 8 |
                grep -Eiom1 "$SERIAL_REGEX" |
                tr '[:lower:]' '[:upper:]' || true
        )"

        if [[ -n "$serial" ]]; then
            printf '%s\n' "$serial"
            return 0
        fi
    fi

    return 1
}

# ------------------------------------------------------------
# Normalize into OPL filename format:
#
# SLUS-21134  -> SLUS_211.34
# SLUS_21134  -> SLUS_211.34
# SLUS_211.34 -> SLUS_211.34
# ------------------------------------------------------------

normalize_opl_serial() {
    local s="$1"

    s="${s//-/_}"
    s="${s//./}"

    if [[ "$s" =~ ^([A-Z]{4})_([0-9]{3})([0-9]{2})$ ]]; then
        echo "${BASH_REMATCH[1]}_${BASH_REMATCH[2]}.${BASH_REMATCH[3]}"
        return
    fi

    echo "$s"
}

# ------------------------------------------------------------
# Find exact trusted CHT match
# ------------------------------------------------------------

find_trusted_cht() {
    local serial="$1"

    find "$TRUSTED_REPO" \
        -type f \
        -iname "${serial}.cht" \
        -print \
        -quit
}

# ------------------------------------------------------------
# Validate native OPL CHT
#
# v0.1a requirements:
# - file exists
# - contains raw 8+8 hex code lines
# - contains at least one code beginning with 9
#
# This does NOT prove the cheat itself is correct.
# It only validates expected native PS2RD structure.
# ------------------------------------------------------------

validate_cht() {
    local file="$1"
    local raw_count
    local master_count

    [[ -f "$file" ]] || return 1

    raw_count="$(
        grep -Ec \
            '^[[:space:]]*[0-9A-Fa-f]{8}[[:space:]]+[0-9A-Fa-f]{8}[[:space:]]*$' \
            "$file" || true
    )"

    master_count="$(
        grep -Ec \
            '^[[:space:]]*9[0-9A-Fa-f]{7}[[:space:]]+[0-9A-Fa-f]{8}[[:space:]]*$' \
            "$file" || true
    )"

    (( raw_count > 0 && master_count > 0 ))
}

# ------------------------------------------------------------
# Determine whether an existing file was generated by any
# version of this script, while preserving truly manual files.
# ------------------------------------------------------------

is_managed_file() {
    local file="$1"

    [[ -f "$file" ]] || return 1
    grep -qF "$MANAGED_PREFIX" "$file"
}

# ------------------------------------------------------------
# Install trusted file
# ------------------------------------------------------------

install_trusted_cht() {
    local source="$1"
    local dest="$2"
    local serial="$3"

    {
        echo "$MANAGED_TAG"
        echo "# Serial: $serial"
        echo "# Source: $TRUSTED_REPO_URL"
        echo "# Classification: TRUSTED NATIVE CHT SOURCE"
        echo
        cat "$source"
    } > "$dest.tmp"

    mv "$dest.tmp" "$dest"
}

# ------------------------------------------------------------
# Build game list
# ------------------------------------------------------------

mapfile -t GAMES < <(
    find "$DVD" "$CD" \
        -maxdepth 1 \

        -type f \
        \( -iname '*.iso' -o -iname '*.zso' \) \
        2>/dev/null |
        sort
)

if (( ${#GAMES[@]} == 0 )); then
    echo "No PS2 ISO/ZSO games found."
    echo
    echo "Checked:"
    echo "  $DVD"
    echo "  $CD"
    exit 0
fi

# ------------------------------------------------------------
# Counters
# ------------------------------------------------------------

scanned=0
identified=0
trusted=0
installed=0
manual_spared=0
invalid=0
nomatch=0
noserial=0

echo "Scanning MX4SIO library..."

# ------------------------------------------------------------
# Main scan
# ------------------------------------------------------------

for game in "${GAMES[@]}"; do
    ((scanned+=1)) || true

    filename="$(basename "$game")"
    raw_serial="$(get_game_serial "$game" || true)"

    if [[ -z "$raw_serial" ]]; then
        echo
        echo "[NO SERIAL] $filename"
        if [[ "${game,,}" == *.zso ]]; then
            echo "  - ZSO content is compressed; put its serial in the filename"
        fi
        ((noserial+=1)) || true
        continue
    fi

    serial="$(normalize_opl_serial "$raw_serial")"
    ((identified+=1)) || true

    echo
    echo "[$serial] $filename"

    source_cht="$(find_trusted_cht "$serial" || true)"

    if [[ -z "$source_cht" ]]; then
        echo "  - No trusted native CHT match"
        ((nomatch+=1)) || true
        continue
    fi

    ((trusted+=1)) || true

    if ! validate_cht "$source_cht"; then
        echo "  ! Native CHT found, but validation failed"
        echo "  -> QUARANTINED"
        cp -f "$source_cht" "$QUARANTINE/$serial.cht"
        ((invalid+=1)) || true
        continue
    fi

    outfile="$CHT/$serial.cht"

    if [[ -f "$outfile" ]] && ! is_managed_file "$outfile"; then
        echo "  ! Existing manual CHT preserved"
        ((manual_spared+=1)) || true
        continue
    fi

    install_trusted_cht \
        "$source_cht" \
        "$outfile" \
        "$serial"

    echo "  + Exact serial match"
    echo "  + Native PS2RD CHT"
    echo "  + 9-type mastercode present"
    echo "  -> INJECTED"

    ((installed+=1)) || true
done

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

echo
echo "============================================================"
echo " SUMMARY"
echo "============================================================"
echo " Games scanned:       $scanned"
echo " Games identified:    $identified"
echo " Trusted matches:     $trusted"
echo " Injected:            $installed"
echo " Quarantined:         $invalid"
echo " No trusted match:    $nomatch"
echo " No serial detected:  $noserial"
echo " Manual files spared: $manual_spared"
echo "============================================================"
echo
echo "Done."
echo
